apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tfsl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tfsl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tfsl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tfsl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tfsl
    spec:
      containers:
      - image: quay.io/quay_xjiang/rhtap-demo-qhzy-tenant/rhtap-demo-app/hacbs-test-project-tfsl@sha256:9019074980433abcd22f921d26b91ad2181dddd3e6836298ec59d8d5b539fdb7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
